name: eterestudio
display_name: Etere Studio Theme
version: 1.0.0
author:
  name: "Marco Silvestroni"
  email: "silvestronimarco@gmail.com"

meta:
  compatibility:
    from: 1.7.5.0
    to: ~
  available_layouts:
    layout-full-width:
      name: Full width layout
      description: Etere studio full width layout

global_settings:
  configuration:
    PS_QUICK_VIEW: false
    NEW_PRODUCTS_NBR: 4
    PS_PNG_QUALITY: 8
  modules:
    to_enable:
      - ps_shoppingcart
      - ps_mainmenu
      - ps_customeraccountlinks
      - ps_languageselector
      - ps_customtext
      - ps_featuredproducts
      - contactform
    to_disable:
      - ps_linklist
      - ps_searchbar
      - ps_emailsubscription
      - ps_banner
      - ps-socialfollow
      - ps_imageslider
      - ps_sharebutton
      - ps_contactinfo
      - ps_sharebuttons
  hooks:
    custom_hooks:
      - name: displayEtereTopLeft
        title: displayEtereTopLeft
        description: Logo icon area
      - name: displayEtereTopRight
        title: displayEtereTopRight
        description: Main menu area
      - name: displayEtereBottomLeft
        title: displayEtereBottomLeft
        description: User logo area
      - name: displayEtereBottomRight
        title: displayEtereBottomRight
        description: Cart icon area
      - name: displayEtereSideRight
        title: displayEtereSideRight
        description: Languange selection area
      - name: displayEtereFormContact
        title: displayEtereSideRight
        description: Languange selection area

    modules_to_hook:
      displayEtereTopLeft:
      displayEtereTopRight:
        - ps_mainmenu
      displayEtereBottomLeft:
        - ps_customeraccountlinks
      displayEtereBottomRight:
        - ps_shoppingcart
      displayEtereSideRight:
        - ps_languageselector
      displayEtereFormContact:
        - contactform
      displayHome:
        - ps_customtext
      displayProductAdditionalInfo:
        - ps_featuredproducts

      #jolly char ~ to pre/post-pend something

  image_types:
    # When theme will be enabled, all image types will be removed
    # Template must declare their image type.
    cart_default:
      width: 80
      height: 80
      scope: [products]
    small_default:
      width: 125
      height: 125
      scope: [products, categories, manufacturers, suppliers]
    medium_default:
      width: 300
      height: 300
      scope: [products, categories, manufacturers, suppliers]
    large_default:
      width: 500
      height: 500
      scope: [products]
    home_default:
      width: 250
      height: 250
      scope: [products]
    category_default:
      width: 960
      height: 350
      scope: [categories]
    product_listing:
      width: 220
      height: 220
      scope: [products, categories, manufacturers, suppliers]
    large_banner:
      width: 960
      height: 400
      scope: [categories]
    product_cover_image:
      width: 300
      height: 400
      scope: [products]
    product_image_1:
      width: 650
      height: 850
      scope: [products]
    product_image_2:
      width: 600
      height: 300
      scope: [products]
    product_image_3:
      width: 350
      height: 700
      scope: [products]
    product_image_4:
      width: 300
      height: 600
      scope: [products]
    product_image_5:
      width: 280
      height: 400
      scope: [products]
    product_image_6:
      width: 350
      height: 490
      scope: [products]

theme_settings:
  # All the settings below can be changed through
  # an interface in the theme's administration panel,
  # and only depend on the theme / shop combination.
  #
  # When this file is parsed by PrestaShop, this configuration
  # key (theme_settings) is copied to a file name settings_n.yml
  # where n is the id of the shop where the theme is installed.
  #
  # When configuration is changed through the interface, only the
  # settings_n.yml file is updated and theme.yml remains unchanged.

  # The layout to use for all pages
  default_layout: layout-full-width
  layouts:
    # Specific layout for some pages
    order: layout-full-width
